Добавление новой логики
ProfessorKauftman/java-filmorate pull request #6
Opened 2024-02-17 07:57 UTC by ProfessorKauftman

Добавил новую логику в приложение, интерфейсы. Переделал код в контроллерах, сервисах и хранилищах под использование внедрения зависимостей.  Добавил методы, позволяющие пользователям добавлять друг друга в друзья, получать список общих друзей и лайкать фильмы.

2024-02-18 10:06 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> alLFilms() {
Вторая буква `L` в слове `all` не в тот регистр уехала

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,
Не стоит выбрасывать такое исключение, так как класс `Film` не должен знать о том, что он работает с чем-то по сети. Это просто объект описывающий данные фильма, а так в него протекает слишком много ненужных знаний, о `response`, `http` кодах ответа и так далее

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final Set<Integer> likes = new HashSet<>();
Для данного поля стоит переопределить `getter`, чтобы не нарушать инкапсуляцию, иначе можно будет изменить внутреннее состояние объекта `film`, а именно его списка лайков, не используя методы `addLike`, `removeLike`. Надо возвращать в методе `getLikes` копию этой коллекции

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final Set<Integer> friends = new HashSet<>();
Замечания аналогичные классу `FIlm`

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private int id = 1;
Идентификатор стоит хранить и обновлять внутри хранилища. 
Часто хранилища, например СУБД, сами могут контролировать обработку идентификатора именно поэтому удобнее хранить идентификатор внутри хранилища

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return new ArrayList<>(filmStorage.allFilms().values());
В теории метод `allFilms` может быть довольно тяжелым и дергать его два раза просто без нужды не особенно хочется. Можно сохранить результат его вызова в локальную переменную, чтобы не вызывать его дважды

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "id can't be negative or equal to 0");
Сервис не должен знать ничего про `http`-взаимодействие, поэтому не стоит здесь выбрасывать такое исключение

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else {
`else` не нужен, так как выше мы выбросили исключение

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else {
`else` не нужен, так как выше мы выбросили исключение

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else {
`else` не нужен, так как выше мы выбросили исключение

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else {
`else` не нужен, так как выше мы выбросили исключение

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Comparator<Film> sortingFilms = (f1, f2) -> {
Не стоит каждый раз объявлять компаратор, он не меняется от вызова к вызову, его можно сделать константой класса

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService {
Замечания аналогичные `FilmService`

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Map<Integer, Film> allFilms();
Такой интерфейс может быть не удобен в дальнейшем, если придется отказаться от хранения данных в виде `Map`

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private static HashMap<Integer, Film> films = new HashMap<>();
Не стоит делать это поле статическим, нам может понадобиться несколько объектов хранилищ, например для кэширования данных. А статическое поле не позволяет нам иметь несколько разных `Map` между объектами класса

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return films;
Это нарушает инкапсуляцию, надо возвращать копию коллекции

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        return users;
Аналогичное замечание про инкапсуляцию

2024-02-18 10:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    Map<Integer, User> allUsers();
Аналогичный совет про `Map`

2024-02-18 11:29 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> alLFilms() {
Исправил!

2024-02-18 11:33 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,
Исправил!

2024-02-18 11:37 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final Set<Integer> likes = new HashSet<>();
Исправил!

2024-02-18 11:42 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final Set<Integer> friends = new HashSet<>();
Исправил!

2024-02-18 11:46 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private int id = 1;
Исправил!

2024-02-18 11:51 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return new ArrayList<>(filmStorage.allFilms().values());
Исправил!

2024-02-18 14:00 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "id can't be negative or equal to 0");
Исправил!

2024-02-18 14:02 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else {
Исправил!

2024-02-18 14:02 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else {
Исправил!

2024-02-18 14:02 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else {
Исправил!

2024-02-18 14:02 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else {
Исправил!

2024-02-18 14:31 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Comparator<Film> sortingFilms = (f1, f2) -> {
Исправил!

2024-02-18 14:42 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +public class UserService {
Исправил!

2024-02-18 14:43 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private static HashMap<Integer, Film> films = new HashMap<>();
Исправил!

2024-02-18 16:20 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        return films;
Исправил!

2024-02-18 16:20 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        return users;
Исправил!

2024-02-18 16:20 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    Map<Integer, User> allUsers();
Исправил!

2024-02-18 16:20 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Map<Integer, Film> allFilms();
Исправил!

2024-02-19 09:45 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-02-25 13:37 UTC, merged