Feat: Добавление новой логики тз-11
ProfessorKauftman/java-filmorate pull request #8
Opened 2024-03-12 18:00 UTC by ProfessorKauftman

Добавление новых сущностей. Тесты. ER - диаграммы.

2024-03-13 07:36 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-03-13 07:36 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getPopularFilms(@Positive @RequestParam(value = "count", defaultValue = "10") int count) {
Нет необходимости в `value`, если оно совпадает с названием переменной

2024-03-13 07:36 UTC, LexLippi commented on src/main/resources/schema.sql
> +film_id INTEGER REFERENCES films(film_id)
1. Оба поля должны быть `not null`
2. В таблице нет `primary key`
3. При удалении фильма не хотим удалить лайк?

2024-03-13 07:36 UTC, LexLippi commented on src/main/resources/schema.sql
> +);
Аналогичные замечания, как и для таблицы ниже

2024-03-13 07:36 UTC, LexLippi commented on src/main/resources/schema.sql
> +name VARCHAR(100) NOT NULL,
Нашел такой замечательный фильм:
https://en.wikipedia.org/wiki/Those_Magnificent_Men_in_Their_Flying_Machines

Его название на русском состоит из 107 символов, на английском из 110, а значит он не влезет в нашу таблицу, чего не хотелось бы. Поэтому советую увеличить размер этого поля.

2024-03-13 07:36 UTC, LexLippi commented on src/main/resources/schema.sql
> +description VARCHAR(200) NOT NULL,
Описание тоже советую увеличить

2024-03-13 07:36 UTC, LexLippi commented on src/main/resources/schema.sql
> +email VARCHAR(50) NOT NULL,
Максимальный размер адреса электронной почты - 254 символа
https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address

2024-03-13 07:36 UTC, LexLippi commented on src/main/resources/schema.sql
> +status boolean
Может быть `null`?

2024-03-13 07:36 UTC, LexLippi commented on src/main/resources/schema.sql
> +friend_id INTEGER REFERENCES users(user_id) on delete cascade,
не хватает `primary key` в таблице

2024-03-13 07:36 UTC, LexLippi commented on src/main/resources/schema.sql
> +drop table IF EXISTS likes CASCADE;
Вот это не стоит хранить в реальной миграции. Кто захочет пользоваться приложением, которое при каждом обновлении вычищает данные из базы?)

2024-03-13 07:36 UTC, LexLippi commented on src/main/resources/data.sql
> +insert into genres (name) values ('Комедия'), ('Драма'), ('Мультфильм'), ('Триллер'), ('Документальный'), ('Боевик');
Можно использовать команду `merge into`

2024-03-14 13:29 UTC, ProfessorKauftman commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getPopularFilms(@Positive @RequestParam(value = "count", defaultValue = "10") int count) {
исправил

2024-03-15 09:52 UTC, ProfessorKauftman commented on src/main/resources/data.sql
> +insert into genres (name) values ('Комедия'), ('Драма'), ('Мультфильм'), ('Триллер'), ('Документальный'), ('Боевик');
исправил

2024-03-15 09:52 UTC, ProfessorKauftman commented on src/main/resources/schema.sql
> +drop table IF EXISTS likes CASCADE;
исправил

2024-03-15 09:52 UTC, ProfessorKauftman commented on src/main/resources/schema.sql
> +friend_id INTEGER REFERENCES users(user_id) on delete cascade,
исправил

2024-03-15 09:52 UTC, ProfessorKauftman commented on src/main/resources/schema.sql
> +status boolean
исправил

2024-03-15 09:52 UTC, ProfessorKauftman commented on src/main/resources/schema.sql
> +email VARCHAR(50) NOT NULL,
исправил

2024-03-15 09:52 UTC, ProfessorKauftman commented on src/main/resources/schema.sql
> +description VARCHAR(200) NOT NULL,
исправил

2024-03-15 09:53 UTC, ProfessorKauftman commented on src/main/resources/schema.sql
> +name VARCHAR(100) NOT NULL,
исправил

2024-03-15 09:53 UTC, ProfessorKauftman commented on src/main/resources/schema.sql
> +);
исправил

2024-03-15 09:53 UTC, ProfessorKauftman commented on src/main/resources/schema.sql
> +film_id INTEGER REFERENCES films(film_id)
исправил

2024-03-16 08:10 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-03-16 11:12 UTC, merged